chore: Update dependencies and just recipes
UN-OSAA/osaa-mvp pull request #1
Opened 2024-11-16 15:55 UTC by pedroheyerdahl

This PR updates project dependencies to resolve conflicts, remove unused libraries, and introduce just recipes for SQLMesh transformations and the complete pipeline (a combination of ingest, transform, and upload steps).

### Dependencies
- Set version constraints for core packages:
  - numpy < 2.0.0
  - pandas < 3.0.0
  - sqlmesh == 0.122.3
- Removed unnecessary dependencies

### Just Recipes
Added new commands:
````bash
just transform # Run SQLMesh transformations
just etl # Run complete pipeline

````
### Other Changes
- Updated .gitignore to exclude system files.
- Enhanced setup documentation for better clarity and onboarding.

2024-11-16 16:05 UTC, db-tycoon-stephen commented on README.md
>  Mirian Lima - mirian.lima@un.org
```suggestion
Mirian Lima (Project Sponsor) - mirian.lima@un.org
Stephen Sciortino (Principal Engineer, Consultant) - stephen.sciortino@un.org; stephen@databasetycoon.com
```

2024-11-16 16:19 UTC, db-tycoon-stephen requested changes
Hey @pedroheyerdahl I got an issue installing the requirements. I'm on 3.12.3. We may need to set a version max in the readme.
Which did you use to run this?
![image](https://github.com/user-attachments/assets/a46ab8ea-3ba9-464f-ba02-028cb2e18edc)

2024-11-16 16:53 UTC, db-tycoon-stephen commented
I resolved it by running the install with python 3.11. Could you add <3.12 to the section in the readme?
Otherwise this is ready to merge!

2024-11-16 23:16 UTC, pedroheyerdahl commented
> I resolved it by running the install with python 3.11. Could you add <3.12 to the section in the readme? Otherwise this is ready to merge!

@db-tycoon-stephen nice catch! version constraint is now clarified in the readme. ty!

2024-11-17 11:47 UTC, db-tycoon-stephen approved these changes
Looks good!

2024-11-17 13:51 UTC, merged